{% set name = "hexbytes" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01312fcd5c57e8a8d2d7dd3274dcf84ea50422aff2abcc2d9fd89ad6a32498e5

build:
  number: 2
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION="{{ version }}"
    - {{ PYTHON }} -m pip install . -vv
    - rm -rf ${SP_DIR}/docs   # [unix]
    - rmdir /s /q %SP_DIR%\docs   # [win]

requirements:
  host:
    - setuptools
    - setuptools-scm
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - hexbytes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/hexbytes
  summary: 'hexbytes: Python `bytes` subclass that decodes hex, with a readable console output'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
