{% set name = "hexbytes" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3fe35c6831ee8fafd048c4c086b986075fc14fd46258fa24ecb8d65745f9a9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - hexbytes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/hexbytes
  summary: 'hexbytes: Python `bytes` subclass that decodes hex, with a readable console output'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
