{% set name = "hexbytes" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a61840c24b0909a6534350e2d28ee50159ca1c9e89ce275fd31c110312cf684

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - hexbytes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/hexbytes
  summary: 'hexbytes: Python `bytes` subclass that decodes hex, with a readable console output'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
