{% set name = "hexbytes" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8253ba54442cd798f52fe77a0bc85cd0cff30266edc22660bd52f1a6e04af51d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0

test:
  imports:
    - hexbytes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/hexbytes
  summary: 'hexbytes: Python `bytes` subclass that decodes hex, with a readable console output'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
